USE UNIVERSITY;
SELECT COUNT(*) AS NET_COUNT 
FROM INSTRUCTOR WHERE ID NOT IN (SELECT ID FROM TEACHES);

SELECT BUILDING, SUM(CAPACITY) AS SUM 
FROM CLASSROOM GROUP BY BUILDING;

SELECT DEPT_NAME, COUNT(DEPT_NAME) AS INSTRUCTOR_COUNT 
FROM INSTRUCTOR GROUP BY DEPT_NAME ORDER BY INSTRUCTOR_COUNT DESC;

SELECT NAME FROM STUDENT WHERE ID IN (SELECT ID FROM TAKES WHERE GRADE IS NOT NULL AND NOT GRADE='F');

SELECT T1.STUDENT_ID, SUM(T2.CREDITS) AS TOTAL_CREDITS FROM 
(SELECT ID AS STUDENT_ID, COURSE_ID FROM TAKES WHERE GRADE IS NOT NULL AND NOT GRADE='F') AS T1 
INNER JOIN COURSE AS T2 ON T1.COURSE_ID=T2.COURSE_ID 
GROUP BY T1.STUDENT_ID;

SELECT COURSE_ID, TITLE FROM COURSE WHERE COURSE_ID NOT IN (SELECT COURSE_ID FROM PREREQ);

SELECT ID,NAME FROM STUDENT WHERE ID IN 
(	SELECT ID FROM TAKES WHERE NOT COURSE_ID IN 
	(SELECT COURSE_ID FROM COURSE WHERE NOT DEPT_NAME='BIOLOGY'));